### ISSUE TITLE
Is it possible to update this to the latest version? 2.0.1201819

### ISSUE THREAD

**Issue by b099l3** [nventive/Binding.PayPaylHereSDK.iOS#5]
I am trying to bind the latest version of the PayPalHereSDK version 2.0.1201819. I came across your repo and thought I might be able to update it to the latest version. Are there any steps that I could follow to do this?

I have run Objective Sharpie on the cocoa pod here https://cocoapods.org/pods/PayPalHereSDKv2 but I am having linker issues. How did you manage to get the native reference settings in the binding projects for the frameworks?

**Comment by huideaki** [comment]
Hey there, I did all of this binding while I was working at nventive.

https://github.com/nventive/Binding.PayPaylHereSDK.iOS/tree/master/XCodeLibrary in this subfolder you can see that there is 3 xcode native project those generates the native references framework that you need to reference in the Native Reference section of the c# iOS Binding project.

As for the framework itself, if I remember correctly, I pulled it from the paypal here ios github directly and then ran objective sharpie on the .framework.

**Comment by b099l3** [comment]
Cool thanks for the update.

**Comment by Premierapp** [comment]
> Cool thanks for the update.

Hi, When generating the binding library for latest SDK version, it generates so many errors.  Do you by any chance have the latest binding library ?
