### ISSUE TITLE
Is this for Xam Android or iOS? 

### ISSUE THREAD

**Issue by rodrigojuarez** [nventive/Binding.PayPaylHereSDK.iOS#6]
In the nuget page you can see Android, but when you try to install the package looks like is for iOS

**Comment by benventive** [comment]
I can only see iOS on my end. Are you checking [this one](https://www.nuget.org/packages/nventive.PayPalHereSDK/)  ?

**Comment by rodrigojuarez** [comment]
Yes, in the nuget page you can see: "A Xamarin.Android binding library for the PayPalHere SDK iOS (https://github.com/paypal/paypal-here-sdk-ios-distribution)"

**Comment by benventive** [comment]
Oh, I see! Hadn't noticed this one. It's definitely for iOS, I'll fix the description

**Comment by rodrigojuarez** [comment]
Thanks! Do you have any pointers about the xam.android implementation? Could I use this code as an starting point?

**Comment by benventive** [comment]
I think someone made a binding for it : https://bitbucket.org/markjackmilian/xam.paypal.droid/wiki/Home
Not sure if it's up to date or working but it should be good starting point!

**Comment by rodrigojuarez** [comment]
I think the previous link is not related to paypal here sdk, but probably will be a good start, thanks again!

**Comment by benventive** [comment]
Very possible. Sorry about that, and I hope you succeed!
